name: libeicsu
version: 1

libraries:
- name: PIL
  version: "1.1.7"

- name: django
  version: "1.5"

handlers:
- url: /static/
  static_path: "library/static"

cron:
    - description: database backup
      url: /backups/RequestAjaxBackup
      schedule: every 720 mins